language: generic 
sudo: required
services: 
  - docker


before_install:
  - winpty docker build -t carva1992/docker-react -f Dockerfile.dev .
  #language: generic 
  #docker run -e CI=true USERNAME/docker-react npm run test


script:
  - winpty docker run -e CI=true carva1992/docker-react npm run test -- --coverage